### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by nikking** [ebemunk/pgnstats#1]
I'm having trouble installing this because the following packages can't be found and aren't included in the repo.

github.com/malbrecht/chess
github.com/malbrecht/chess/pgn
github.com/pkg/profile

I'm new to Go so it could also be me doing something stupid. Can you help me with the install? Thanks!

**Comment by ebemunk** [comment]
Hi!

This is generally how Go packages are distributed. You will need to get the dependencies (remote packages) by running `go get github.com/malbrecht/chess` etc, or via your IDE if it supports automatically getting them (Atom with the go-plus package does).

Go is quite opinionated on how you need to structure your source folders, I'd recommend reading through [How to write Go Code](https://golang.org/doc/code.html) which will take you through the steps you need to set up Go and start being able to build packages and write your own.
