### ISSUE TITLE
I could not run the ./pgnstats

### ISSUE THREAD

**Issue by emoshkovich** [ebemunk/pgnstats#2]
I get an error saying -bash: ./pgnstats: No such file or directory. Where is the .sh file to run? Or what file should I run?

**Comment by ebemunk** [comment]
Hi @emoshkovich , this is a Go package (https://golang.org/) and the binary is not distributed with or included in this repository. You will need to download and setup golang, after which you can run `go get github.com/ebemunk/pgnstats` which will download the repo, and afterwards you can do `go install github.com/ebemunk/pgnstats` to have the executable available on your `GOPATH`.
