### ISSUE TITLE
Visualize json output?

### ISSUE THREAD

**Issue by jeRosengren** [ebemunk/pgnstats#4]
Hi!

What tool do you recommend for visualizing the json output?
Just had a quick look at this project. Looks very neat :)

/Jon Even

**Comment by nikking** [comment]
I forked this other repo from ebemunk to do that. https://github.com/ebemunk/chess-dataviz

**Comment by ebemunk** [comment]
Hello @jeRosengren thanks for the interest. As @nikking mentioned you might be able to use chess-dataviz for that, these two were companion projects. The recent changes to this repo might have changed that slightly. Personally I use d3 to visualize this stuff.
