### ISSUE TITLE
# command-line-arguments

### ISSUE THREAD

**Issue by DrShams** [ebemunk/pgnstats#5]
Hello ebemunk
I'm new in Go so I don't understand what have I done wrong
C:\Users\Shams\Desktop\ChessProject\pgnstats>go run pgnstats.go -h 
will return next issue what 
```
# command-line-arguments
.\pgnstats.go:38:11: undefined: Read
.\pgnstats.go:40:20: undefined: GameStats
.\pgnstats.go:47:4: undefined: Parse
.\pgnstats.go:61:15: undefined: OpeningMove
.\pgnstats.go:68:4: undefined: GetStats
.\pgnstats.go:86:10: undefined: NewGameStats
.\pgnstats.go:104:21: undefined: PosMap
.\pgnstats.go:121:20: undefined: GameStats
```
What's the problem or I launch that script wrong?

**Comment by ebemunk** [comment]
what version of go do you have installed? i usually run it by `go run . -otherOptsHere`

**Comment by DrShams** [comment]
Thank you vey much! Understood I had to write:
`go run pgnstats.go Gamestats.go Heatmap.go file.go movetrack.go openingmove.go getstats.go stats.go -f test.pgn -o test.json`
How can I use that file which I get in .json in visualisation?Or it should be only in text format?

**Comment by ebemunk** [comment]
pgnstats can be a companion to chess-dataviz, but it's output is not a drop-in for the charts. the file given by the `-o` flag needs to be massaged to fit the use-case.
