### ISSUE TITLE
Heatmap visualization after pgnstats

### ISSUE THREAD

**Issue by DrShams** [ebemunk/pgnstats#6]
Hello ebemunk and happy new year. I'm trying to do heatmap visualization and observed that after pgnstats.go script the file on the output has the next view:

`Heatmaps":{"SquareUtilization":[{"B":23,"K":25,"N":16,"Q":128,"R":245,"b":39,"k":72,"n":8,"q":48,"r":297}, ...`and 63 other squares
but html visualization form requires next form:

`heatmaps":{"squareUtilization":[{"p":{"w":11,"b":0},"n":{"w":6,"b":5},"b":{"w":16,"b":41},"r":{"w":124,"b":178},"q":{"w":34,"b":48},"k":{"w":2,"b":13},"all":{"w":193,"b":285}}, ...`and also 63 other squares

So there is Bishop->King->Knight->Queen->Rook
But requires also Pawn and 'all'
What is it "all" and is that possible use pgnstats.go script for Heatmaps visualization?

**Comment by ebemunk** [comment]
it looks like they have a bit of a different structure, and that `pgnstats` changed the format with the latest update. you might be able to get the correct format by using version from an earlier commit https://github.com/ebemunk/pgnstats/tree/dcf19bb79faf8e8d9604c1d6ba8257ebdb29f2d5 seems like it will have the same format then.

**Comment by DrShams** [comment]
Wow that is good! It works without corrections. New version of pgnstats does not stack with visualisation, thanks a lot! Everything is working well now, but "movepaths" visualization or Journey of the white queen's knight is not working, "interactive" also is not working as in new version too.

**Comment by ebemunk** [comment]
Yeah unfortunately `pgnstats` and `chess-dataviz` are not guaranteed to be compatible as they aim to do different things. Hopefully you can transform the output to something that you can use for your use-case.
